(()=>{const $=s=>document.querySelector(s),E=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),D=d=>new Date(d).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'});
function clean(h){const d=new DOMParser().parseFromString(h,'text/html');d.querySelectorAll('script,iframe,object,embed,style,link,meta,form').forEach(n=>n.remove());d.querySelectorAll('*').forEach(n=>[...n.attributes].forEach(a=>{if(/^on/i.test(a.name)||/javascript:/i.test(a.value))n.removeAttribute(a.name)}));return d.body.innerHTML}
const seed=()=>fetch('/data/chakras.json').then(r=>r.json());
if($('#bl'))Promise.all([seed(),fetch('/api/articles').then(r=>r.json()).catch(()=>({articles:[]}))]).then(([s,r])=>{$('#bl').innerHTML=[s,...(r.articles||[])].map(x=>`<a class="bc" href="/article?id=${x.id}"><img src="${x.cover}" alt=""><div><h3>${E(x.titre)}</h3><p class="meta">${D(x.date)} | ${E(x.auteur)}</p><p>${E(x.extrait||'')}</p><span class="rm">Lire la suite →</span></div></a>`).join('')});
if($('#art')){const id=new URLSearchParams(location.search).get('id')||'chakras';
(id==='chakras'?seed():fetch('/api/articles?id='+encodeURIComponent(id)).then(r=>r.ok?r.json():Promise.reject())).then(a=>{document.title=a.titre+" | Bien'+";
$('#art').innerHTML=`<div class="art"><img src="${a.cover}" alt=""><div><h1>${E(a.titre)}</h1><p class="meta">${D(a.date)} | ${E(a.auteur)}</p><div class="ac">${clean(a.contenu)}</div></div></div><div class="art" style="margin-top:30px"><div><h2>Commentaires</h2><div id="cm"></div><form id="cf2"><h3 style="font-size:1.3rem;margin:20px 0 6px">Laisser un commentaire</h3><p id="rt" class="rt"></p><label>Nom</label><input name="nom" required maxlength="60"><label>E-mail (non publié)</label><input type="email" name="email" required><label>Message</label><textarea name="message" rows="4" required maxlength="1500"></textarea><input name="_gotcha" style="display:none" tabindex="-1" autocomplete="off"><button class="b bg bl" style="border:0;cursor:pointer">Publier le commentaire</button><p class="er" id="ce"></p></form><div class="ok" hidden><svg viewBox="0 0 52 52"><circle cx="26" cy="26" r="24"/><path d="M14 27l8 8 16-16"/></svg><h3>Merci !</h3><p>Votre commentaire sera publié après validation par Sandrine. 🌸</p></div></div></div>`;
let par='';const T=a.titre;
const rd=(c,p,dp)=>c.filter(x=>(x.parent||'')===p).map(x=>`<div class="cm" style="margin-left:${Math.min(dp,3)*22}px"><b>${E(x.nom)}</b>${x.admin?'<span class="au">Auteure</span>':''}<small>${D(x.date)}</small><p>${E(x.message)}</p><a href="#cf2" class="rp2" data-r="${x.id}" data-n="${E(x.nom)}">Répondre</a></div>`+rd(c,x.id,dp+1)).join('');
fetch('/api/comments?article='+id).then(r=>r.json()).then(r=>{const c=r.comments||[];$('#cm').innerHTML=c.length?rd(c,'',0):'<p>0 commentaire</p>';document.querySelectorAll('.rp2').forEach(l=>l.onclick=()=>{par=l.dataset.r;$('#rt').innerHTML=`Réponse à <b>${l.dataset.n}</b> · <a href="#" id="rx">annuler</a>`;$('#rx').onclick=e=>{e.preventDefault();par='';$('#rt').textContent=''}})}).catch(()=>{});
const f=$('#cf2');f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;try{const d=Object.fromEntries(new FormData(f));d.article=id;d.parent=par;const r=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw 0;
fetch('https://formspree.io/f/xvkgvwel',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({_subject:(par?'Nouvelle réponse':'Nouveau commentaire')+' à valider : '+T,nom:d.nom,email:d.email,message:d.message,article:T,validation:location.origin+'/editeur'})}).catch(()=>{});
f.hidden=true;$('.ok').hidden=false}catch(_){b.disabled=false;$('#ce').textContent="Erreur : vérifiez les champs et réessayez."}}}).catch(()=>{$('#art').innerHTML='<p class="sub">Article introuvable.</p>'})}})();
