(()=>{const $=s=>document.querySelector(s),E=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),J=(u,o={})=>fetch(u,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...o});
const rs=(f,w,q)=>new Promise(r=>{const i=new Image,u=URL.createObjectURL(f);i.onload=()=>{const k=Math.min(1,w/i.width),c=document.createElement('canvas');c.width=i.width*k;c.height=i.height*k;c.getContext('2d').drawImage(i,0,0,c.width,c.height);URL.revokeObjectURL(u);r(c.toDataURL('image/jpeg',q))};i.src=u});
const ed=$('#ed');let rg,cover='';
document.addEventListener('selectionchange',()=>{const s=getSelection();if(s.rangeCount&&ed.contains(s.anchorNode))rg=s.getRangeAt(0)});
const cmd=(c,v)=>{ed.focus();if(rg){const s=getSelection();s.removeAllRanges();s.addRange(rg)}document.execCommand('styleWithCSS',false,true);document.execCommand(c,false,v||null)};
document.querySelectorAll('.tb button[data-c]').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>cmd(b.dataset.c,b.dataset.v)});
$('#ff').onchange=e=>{if(e.target.value)cmd('fontName',e.target.value);e.target.value=''};$('#fs').onchange=e=>{if(e.target.value)cmd('fontSize',e.target.value);e.target.value=''};
$('#im').onclick=()=>$('#if').click();$('#if').onchange=async e=>{const f=e.target.files[0];if(f)cmd('insertImage',await rs(f,900,.75));e.target.value=''};
$('#cv').onchange=async e=>{const f=e.target.files[0];if(!f)return;cover=await rs(f,800,.75);$('#cp').src=cover;$('#cp').hidden=false};
const ask=m=>new Promise(r=>{const d=document.createElement('div');d.className='ckb';d.innerHTML=`<div class="ckc cfm"><h4>Confirmation</h4><p>${m}</p><div class="bt"><button data-v="0">Annuler</button><button class="d" data-v="1">Oui, supprimer</button></div></div>`;d.onclick=ev=>{const v=ev.target.dataset.v;if(v!==undefined||ev.target===d){d.remove();r(v==='1')}};document.body.appendChild(d)});
async function load(){const[a,c]=await Promise.all([J('/api/articles').then(r=>r.json()),J('/api/comments?all=1').then(r=>r.json())]);
const T={chakras:'Les chakras, portails de notre Structure Globale Vibratoire'};(a.articles||[]).forEach(x=>T[x.id]=x.titre);
$('#al').innerHTML=(a.articles||[]).map(x=>`<p><a href="/article?id=${x.id}">${E(x.titre)}</a> <button class="b bv sm" data-del="${x.id}">Supprimer</button></p>`).join('')||'<p>Aucun article ajouté pour le moment.</p>';
const by={};(c.comments||[]).forEach(x=>(by[x.article]=by[x.article]||[]).push(x));
const tree=(l,p,d)=>l.filter(x=>(x.parent||'')===p).map(x=>`<div class="cm" style="margin-left:${Math.min(d,3)*22}px"><b>${E(x.nom)}</b>${x.admin?'<span class="abdg">Auteure</span>':''}<small>${E(x.email||'')} · ${x.approved?'✅ publié':'⏳ à valider'}</small><p>${E(x.message)}</p>${x.approved?'':`<button class="b bg sm" data-ok="${x.article}/${x.id}">Valider</button> `}${x.approved?`<button class="b bv sm" data-rp="${x.id}">Répondre</button> `:''}<button class="b bv sm" data-rm="${x.article}/${x.id}">Supprimer</button><div class="rpb" id="rb${x.id}" hidden><textarea rows="2" placeholder="Votre réponse…"></textarea><button class="b bg sm" data-send="${x.article}/${x.id}">Envoyer la réponse</button></div></div>`+tree(l,x.id,d+1)).join('');
$('#cl').innerHTML=Object.keys(by).map(k=>{const l=by[k],n=l.filter(x=>!x.approved).length;return `<h4 class="ah">${E(T[k]||k)} ${n?`<span class="nb">${n} à valider</span>`:''} <button class="b bv sm" data-all="${k}">Tout supprimer</button></h4>`+tree(l,'',0)}).join('')||'<p>Aucun commentaire.</p>';
const on=(s,f)=>document.querySelectorAll(s).forEach(b=>b.onclick=()=>f(b));
on('[data-del]',async b=>{if(await ask('Êtes-vous sûre de vouloir supprimer cet article ? Cette action est définitive et supprimera aussi tous ses commentaires.')){await J('/api/articles?id='+b.dataset.del,{method:'DELETE'});load()}});
on('[data-ok]',async b=>{const[article,id]=b.dataset.ok.split('/');await J('/api/comments',{method:'PATCH',body:JSON.stringify({article,id})});load()});
on('[data-rm]',async b=>{const[a,i]=b.dataset.rm.split('/');if(await ask('Supprimer ce commentaire ? Ses réponses seront supprimées aussi.')){await J(`/api/comments?article=${a}&id=${i}`,{method:'DELETE'});load()}});
on('[data-all]',async b=>{if(await ask('Supprimer tous les commentaires de cet article ? Cette action est définitive.')){await J(`/api/comments?article=${b.dataset.all}&all=1`,{method:'DELETE'});load()}});
on('[data-rp]',b=>{const x=$('#rb'+b.dataset.rp);x.hidden=!x.hidden});
on('[data-send]',async b=>{const[article,parent]=b.dataset.send.split('/'),m=b.previousElementSibling.value.trim();if(!m)return;await J('/api/comments',{method:'POST',body:JSON.stringify({article,parent,message:m})});load()})}
const show=()=>{$('#lg').hidden=true;$('#ad').hidden=false;load()};
J('/api/login').then(r=>r.json()).then(r=>r.admin&&show()).catch(()=>{});
$('#lf').onsubmit=async e=>{e.preventDefault();const r=await J('/api/login',{method:'POST',body:JSON.stringify({password:$('#pw').value})});r.ok?show():$('#le').textContent='Mot de passe incorrect'};
$('#lo').onclick=async()=>{await J('/api/login',{method:'DELETE'});location.reload()};
$('#pb').onclick=async()=>{const t=$('#tt').value.trim(),h=ed.innerHTML.trim();$('#pe').textContent='';if(!t||!ed.textContent.trim()&&!ed.querySelector('img')){$('#pe').textContent='Titre et contenu requis.';return}
$('#pb').disabled=true;const ex=$('#ex').value.trim()||ed.textContent.trim().slice(0,200)+'…';
const r=await J('/api/articles',{method:'POST',body:JSON.stringify({titre:t,extrait:ex,cover,contenu:h})});$('#pb').disabled=false;
if(r.ok){const d=await r.json();location.href='/article?id='+d.id}else $('#pe').textContent=r.status===413?'Images trop lourdes : réduisez-en.':'Erreur à la publication.'}})();
