const $=s=>document.querySelector(s),hd=$('.hd'),nav=$('.nav');
addEventListener('scroll',()=>hd.classList.toggle('s',scrollY>60),{passive:true});
$('.burger').onclick=()=>nav.classList.toggle('o');
$('.dd>a').onclick=e=>{if(innerWidth<=900){e.preventDefault();$('.dd').classList.toggle('o')}};
document.querySelectorAll('.card').forEach(c=>c.onclick=()=>{document.querySelectorAll('.card').forEach(o=>o!==c&&o.classList.remove('a'));c.classList.toggle('a')});
const BTN=(l)=>`<div style="text-align:center;margin-top:24px"><a class="b bv bl" href="/rdv">${l||'Me Contacter'}</a></div>`;
const M={
holistique:['Soin Énergétique Holistique','Un accompagnement global qui va au-delà des symptômes',`<p>À la croisée de mes formations certifiées et de la guidance de mes perceptions, le soin se dessine pour réaligner l'intégralité de votre structure, de vos corps subtils jusqu'au cœur de vos cellules.</p><p>Chaque blocage, qu'il soit lié à votre histoire, à votre lignée générationnelle ou à vos mémoires karmiques, porte une leçon. Mon rôle est de vous aider à intégrer ce message pour transformer l'épreuve en un trésor de conscience.</p><p>J'agis sur les fréquences vibratoires de votre être pour permettre un ancrage profond et un retour à votre lumière initiale.</p><p><b>Accompagnement personnalisé :</b> je préconise entre deux et cinq séances afin de stabiliser votre transformation intérieure.</p><p><b>80€</b> la séance · tarif solidaire <b>60€</b><br>💎 Option : bijou en pierre naturelle sur mesure et magnétisé</p>`],
antitrauma:['Accompagnement Antitrauma','Apaiser l\'empreinte du passé et retrouver un sentiment de sécurité intérieure',`<p>Certains événements continuent de nous affecter bien après avoir pris fin. Le corps, les émotions et les pensées peuvent continuer à réagir comme si le danger était encore présent.</p><p>L'accompagnement offre un espace sécurisant, bienveillant et sans jugement. Il ne s'agit pas de revivre l'événement : on part de ce qui est présent aujourd'hui, à votre rythme.</p><p>Le protocole se déroule sur un minimum de trois séances espacées d'environ une semaine, à réserver dès le début.</p><p><b>80€</b> la séance (3 séances)</p><p><i>Cet accompagnement est complémentaire et ne remplace pas un suivi médical ou psychologique.</i></p>`,'Réserver mes 3 premières séances'],
constellation:['Constellation Familiale Énergétique','Libérez-vous des schémas du passé',`<p>La constellation familiale énergétique NIJI met en lumière les loyautés invisibles et schémas répétitifs inconscients. Les problématiques sont classées selon 3 axes : <b>les Drames</b> (violence, morts prématurées, maladies), <b>les Problèmes</b> (argent, addictions, emprise, secrets de famille) et <b>les Blessures de l'Âme</b> (trahison, rejet, abandon, peur).</p><p>Ce travail permet de se libérer des poids émotionnels transmis de génération en génération et d'améliorer durablement vos relations.</p><p><b>100€</b> la séance</p>`],
formation:['Formation Reiki','3 niveaux + Maître Reiki',`<p>Apprenez les gestes du protocole Reiki et ses symboles au cours des 3 niveaux, pour soigner les autres et vous-même par des auto-soins.</p><p>Apaiser ses émotions · libérer tensions et douleurs · développer ses capacités de guérison · accompagner les autres.</p><p><b>Tarif sur demande</b> · formation personnalisée selon votre niveau</p>`],
reiki:['Soin Reiki','Méthode ancestrale japonaise',`<p>Soin par imposition des mains et utilisation de symboles. L'énergie se diffuse à travers les mains et travaille là où il y a besoin. Les chakras sont harmonisés.</p><p>Apaisement · relaxation profonde · vitalité · équilibre émotionnel · libération des tensions du corps et de l'esprit.</p><p><b>50€</b> la séance</p>`],
harmonisation:['Harmonisation des Lieux','Purification énergétique de votre habitat',`<img src="/assets/lieux.webp" alt="Schéma harmonisation"><p>Ce soin détecte les déséquilibres énergétiques d'un lieu, d'une voiture, d'un site internet ou de réseaux sociaux, puis nettoie, purifie et harmonise les énergies des personnes concernées.</p><p>Il s'agit de travailler sur la mémoire des murs et des sols, les nuisances géobiologiques (réseau Hartmann, réseau Curry, cheminées cosmo-telluriques) et les énergies négatives, ainsi que sur l'harmonisation des habitants.</p><p><b>Méthode :</b> travail sur plan de l'habitation en radiesthésie et en énergétique.</p><p><b>À partir de 200€</b> · tarif adapté selon la superficie</p>`,'Demander un Devis'],
meditation:['Atelier Méditation','Cultiver la paix intérieure en groupe',`<p>Atelier collectif mensuel pour explorer différentes pratiques méditatives et cultiver la paix intérieure en groupe.</p><p>🧘‍♀️ Me suivre sur Facebook ou Instagram pour connaître les prochaines dates.</p>`,"S'inscrire"]};
function openM(k){const[a,b,c,d]=M[k];$('#mc').innerHTML=`<button class="x" onclick="closeM()">×</button><div class="mh"><h2>${a}</h2><p><i>${b}</i></p></div><div class="mb">${c}${BTN(d)}</div>`;$('#md').classList.add('a');document.body.style.overflow='hidden'}
function closeM(){$('#md').classList.remove('a');document.body.style.overflow=''}
if($('#md')){$('#md').onclick=e=>e.target.id==='md'&&closeM();addEventListener('keydown',e=>e.key==='Escape'&&closeM())}
if($('#trk'))fetch('/data/avis.json').then(r=>r.json()).then(a=>{if(!a.length)return;const h=a.map(r=>`<a class="rv" href="${GOOGLE}" target="_blank" rel="noopener"><div class="st">★★★★★</div><p>${r.texte}</p><b>${r.nom}</b></a>`).join('');$('#trk').innerHTML=h+h;$('#mar').hidden=false}).catch(()=>{});
const cf=document.getElementById('cf');if(cf)cf.onsubmit=async e=>{e.preventDefault();const b=cf.querySelector('button');b.disabled=true;b.textContent='Envoi…';try{const r=await fetch(cf.action,{method:'POST',body:new FormData(cf),headers:{Accept:'application/json'}});if(!r.ok)throw 0;cf.hidden=true;document.querySelector('.ok').hidden=false}catch(_){b.disabled=false;b.textContent='Envoyer';alert("Une erreur est survenue. Écrivez-moi par e-mail ou WhatsApp.")}};
